# Grace period duration in minutes
grace-period-minutes: 20

# Multiplier for the day/night cycle speed. 1.0 is default speed.
day-night-cycle-multiplier: 4.0

# Survivor Locator Settings
survivor-locator:
  # Interval in minutes to check for survivors
  check-interval-minutes: 2
  # Number of players remaining to trigger the location broadcast
  trigger-player-count: 3

# Skill Cooldowns (in seconds)
cooldowns:
  solar-flare: 20
  suns-spear: 15
  afterglow: 25
  shadow-dash: 20
  moons-chain: 20
  shadow-wings: 15
  moon-smash: 10
  stealth: 23
